name:                Liktor János
markdown:            kramdown
theme:               jekyll-theme-slate
permalink:           /:categories/:year/:month/:day/:title/
layout:              default
title:               www.liktorjanos.hu
tagline:             My own website for notes
description:         My own website for notes, experiment with github, jekyll and stuff...
url:                 https://www.liktorjanos.hu
baseurl:             ''
paginate:            5
plugins:          [jekyll-paginate]
