theme: jekyll-theme-merlot

# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
layout:              luc1
title:               www.liktorjanos.hu
tagline:             My own website for notes
description:         My own website for notes, experiment with github, jekyll and stuff...
url:                 https://www.liktorjanos.hu
baseurl:             ''
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]
